<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>br.ufc.quixada.sd</groupId>
    <artifactId>mural-pixel-art</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Mural Pixel Art - Sistemas Distribuídos</name>
    <description>QXD0043 - Trabalhos 1 ao 4</description>

    <modules>
        <module>shared</module>
        <module>trabalho-1</module>
        <module>trabalho-2</module>
        <module>trabalho-3</module>
        <module>trabalho-4</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
</project>
